### ISSUE TITLE
XDMA kernel driver maturity

### ISSUE THREAD

**Issue by hinxx** [MicroTCA-Tech-Lab/damc-tck7-fpga-bsp#1]
In your opinion Jan, what is the XDMA kernel driver maturity level?
Have you been running any stress tests?
Would you recommend any of the existing tools to do that?

I'm thinking about moving large amounts of data between CPU and AMC and hoping for stable operation wo/ errors ; I guess how to detect those error, and what they might be manifested as is the question.

FYI, there is a github repo of the XDMA at https://github.com/Xilinx/dma_ip_drivers/tree/master/XDMA/linux-kernel, but it does not work for me (see the issue posted on that Github project). It makes my CPU reboot due to kernel panic (not investigated yet why).

The driver at https://github.com/ramonaoptics/xilinx-dma-driver does work for me and I can see 3.5 GB/s rates when using x4 Gen3 PCIe link on Struck SIS8300-KU.

We are seriously looking into having XDMA as basis design for upcoming AXI based ESS framework on Struck SIS8300-KU and possibly IOxOS IFC1401, and are interested in other users experience with the IP core as well as with AR65444 kernel driver that comes along. Any comments are welcomed!

**Comment by j-marjanovic** [comment]
Hi Hinko,

we at Tech Lab have started using this driver and generally we do not see major problems with it. The command in the question (`performance -s 64 -c 1`) also throws a Kernel panic on both of the boards we have (TCK7 and SIS8300-KU), and I guess there might be some problem on how the driver cleans up after the performance test. In any case, this performance measurement ioctl() are not the part of the normal data flow in a normal operation, a more relevant measurements are `dma_from_device` and `dma_to_device` (this is how then application really gets the data out of the card).

Overall I think it is a significant step forward for an FPGA manufacturer to provide a decent Linux driver (I remember the time of Virtex 5 when this was not the case), and we are happy to use it. There are some limitations which one needs to learn and live with it, i.e. 64-bit accesses to AXI4-Lite port block the interface:

![64-bit access on AXI4-Lite port](https://user-images.githubusercontent.com/5960097/60790350-94b06a80-a161-11e9-8e67-3de85d683990.png)
